#!/bin/bash
#
# run_iwyu.sh - Run Include What You Use (IWYU) on ESP-IDF projects
#
# Usage: ./run_iwyu.sh [target_file]
#   target_file: path to the file to analyze (default: main/main.cpp)
#
# Prerequisites:
#   - idf.py build must have been run to generate build/compile_commands.json
#   - iwyu-tool must be installed
#
# The main challenge this script solves: IWYU uses its own Clang frontend,
# not the Xtensa cross-compiler, so we need to carefully replicate the
# cross-compilation environment for Clang to parse ESP-IDF headers correctly.

set -e

IDF_PATH="~/esp/v5.5.2/esp-idf"

# ---------------------------------------------------------------------------
# Locate the Xtensa toolchain from the build database
#
# compile_commands.json contains the full path to the cross-compiler, e.g.:
#   /home/user/.espressif/tools/xtensa-esp-elf/<ver>/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc
# We walk up two directories from the binary to get the toolchain root.
# ---------------------------------------------------------------------------
TOOLCHAIN_BASE=$(python3 -c "
import json, os
with open('build/compile_commands.json') as f:
    cmds = json.load(f)
compiler = cmds[0]['command'].split()[0]
print(os.path.dirname(os.path.dirname(compiler)))
")

# The sysroot contains the Xtensa-specific standard library headers (stdint.h,
# stdio.h, etc.). Without this, Clang falls back to the host's 64-bit headers
# which conflict with ESP-IDF's 32-bit assumptions.
SYSROOT="$TOOLCHAIN_BASE/xtensa-esp-elf"

# GCC internal headers (stddef.h, stdarg.h, etc.) live separately from the
# sysroot under the lib/gcc directory.
GCC_INCLUDES="$TOOLCHAIN_BASE/lib/gcc/xtensa-esp-elf/14.2.0/include"

# C++ standard library headers, plus the target-specific subdirectory which
# contains ABI and configuration headers for xtensa-esp-elf.
CXX_INCLUDES="$SYSROOT/include/c++/14.2.0"
CXX_TARGET_INCLUDES="$CXX_INCLUDES/xtensa-esp-elf"

TARGET_FILE=${1:-"main/main.cpp"}

# ---------------------------------------------------------------------------
# Patch compile_commands.json
#
# The database generated by idf.py contains flags that Clang doesn't
# understand (they're GCC-specific), and -Werror=all which would cause IWYU
# to abort on any warning. We strip these out into a temporary copy so the
# original build database is left untouched.
# ---------------------------------------------------------------------------
PATCHED_DB=$(mktemp /tmp/compile_commands_XXXXX.json)

python3 - "$PATCHED_DB" << 'PYEOF'
import json, shlex, sys

with open('build/compile_commands.json') as f:
    cmds = json.load(f)

# Flags that are valid for GCC/Xtensa but unknown to Clang.
GCC_ONLY_FLAGS = {
    '-mlongcalls',                # Xtensa-specific call instruction range flag
    '-fstrict-volatile-bitfields', # GCC extension for volatile bitfield layout
    '-fno-tree-switch-conversion', # GCC tree optimization flag
}

for c in cmds:
    tokens = shlex.split(c['command'])
    filtered = []
    for flag in tokens:
        if flag.startswith('-Werror'):
            # Drop all -Werror variants. IWYU runs Clang which has stricter
            # warnings than GCC, so many ESP-IDF headers trigger warnings
            # that would abort the analysis before IWYU can produce results.
            pass
        elif flag in GCC_ONLY_FLAGS:
            pass
        else:
            filtered.append(flag)
    c['command'] = ' '.join(shlex.quote(t) for t in filtered)

with open(sys.argv[1], 'w') as f:
    json.dump(cmds, f, indent=2)
PYEOF

echo "Toolchain base : $TOOLCHAIN_BASE"
echo "Sysroot        : $SYSROOT"
echo "Running IWYU on $TARGET_FILE..."

# ---------------------------------------------------------------------------
# Noise filter for IWYU output
#
# Even with the patches above, some noisy-but-harmless warnings remain.
# We filter these from stdout so the actual IWYU suggestions are readable,
# while tee still captures everything to /tmp/iwyu_raw.txt for inspection.
# ---------------------------------------------------------------------------
FILTER='no private include|mlongcalls|fstrict-volatile|fno-tree-switch|macro-redefined|Wmacro|extern-c-compat'

iwyu-tool -p "$PATCHED_DB" "$TARGET_FILE" -- \
    `# Suppress unknown Clang warning flags inherited from the build` \
    -Wno-unknown-warning-option \
    -Wno-error \
    -Wno-extern-c-compat \
    -Wno-macro-redefined \
    `# ESP-IDF headers cast between pointer and uint32_t assuming 32-bit pointers` \
    -Wno-int-to-void-pointer-cast \
    -Wno-pointer-to-int-cast \
    -Wno-int-to-pointer-cast \
    -ferror-limit=0 \
    `# Tell IWYU not to suggest forward declarations (noisy and unhelpful in C)` \
    -Xiwyu --no_fwd_decls \
    `# Target triple tells Clang to use 32-bit pointer size, matching the ESP32` \
    -target xtensa-esp-elf \
    `# __XTENSA__ is normally defined by the cross-compiler itself, not via -D.` \
    `# Since IWYU uses its own Clang, we must inject it manually so that ESP-IDF` \
    `# headers (e.g. spinlock.h) take the Xtensa code path instead of RISC-V.` \
    -D__XTENSA__ \
    -DCONFIG_IDF_TARGET_ARCH_XTENSA=1 \
    -DCONFIG_IDF_TARGET_ESP32=1 \
    `# lwIP defines ssize_t as 'int' only when SSIZE_MAX is not defined.` \
    `# By defining it here, lwIP skips its typedef and avoids conflicting with` \
    `# the sysroot's definition of ssize_t as '_ssize_t' (aka long).` \
    -DSSIZE_MAX=2147483647 \
    `# Prevent lwIP from including unistd.h, which would cause a second` \
    `# ssize_t conflict with the sysroot.` \
    -DLWIP_NO_UNISTD_H=1 \
    `# Use the Xtensa sysroot for standard headers instead of the host's.` \
    `# ESP-IDF's newlib platform_include is listed first so its overrides` \
    `# (e.g. sys/errno.h) take precedence over the bare sysroot versions.` \
    --sysroot="$SYSROOT" \
    -isystem "$IDF_PATH/components/newlib/platform_include" \
    -isystem "$SYSROOT/include" \
    -isystem "$GCC_INCLUDES" \
    -isystem "$CXX_INCLUDES" \
    -isystem "$CXX_TARGET_INCLUDES" \
    2>&1 | tee /tmp/iwyu_raw.txt | grep -Ev "$FILTER"

rm -f "$PATCHED_DB"

# Print a clean summary of just the actionable IWYU suggestions.
echo ""
echo "=== IWYU SUGGESTIONS ==="
grep -E "should add|should remove|has correct|has incorrect" /tmp/iwyu_raw.txt

# Action the suggestions.
echo "=== APPLYING CHANGES ==="
iwyu-fix-includes --nosafe_headers < /tmp/iwyu_raw.txt
