name: ESP-IDF Component Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-pipi:
    name: Run Pipi Tests
    runs-on: ubuntu-latest
    container: espressif/idf:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Custom Clang Toolchain
        run: |
          apt-get update && apt-get install -y clang lld llvm
          cat .github/workflows/toolchain-clang-linux.cmake > $IDF_PATH/tools/cmake/toolchain-clang-linux.cmake

      - name: Fix Git Directory Permissions
        run: git config --global --add safe.directory '*'

      - name: Build and Run Host Tests
        shell: bash
        env:
          CC: clang
          CXX: clang++
        run: |
          . $IDF_PATH/export.sh
          cd esp/speaker-netsender/components/pipi/host_tests/test_pipi
          idf.py --preview set-target linux
          idf.py build -DENABLE_TESTS=ON
          ./build/test_pipi.elf
